using Dapper;
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Npgsql;
using OraiWebhookManager.Application.Interfaces;
using OraiWebhookManager.Application.Models;
using OraiWebhookManager.Domain.Entities;
using OraiWebhookManager.Domain.Enums;
using OraiWebhookManager.Infrastructure.Persistence.Repositories;
using Xunit;

namespace OraiWebhookManager.IntegrationTests;

public class PubSubWebhookInboxRepositoryTests : IAsyncLifetime
{
    private readonly string _schemaName = $"test_pubsub_{Guid.NewGuid():N}";
    private string _isolatedConnectionString = string.Empty;
    private IWebhookInboxRepository _inboxRepository = null!;
    private IWebhookProcessorRepository _processorRepository = null!;

    public async Task InitializeAsync()
    {
        var rawConnection = Environment.GetEnvironmentVariable("TEST_POSTGRES_CONNECTION");
        if (string.IsNullOrWhiteSpace(rawConnection))
        {
            throw new InvalidOperationException(
                "TEST_POSTGRES_CONNECTION environment variable is required to execute Phase 1 PostgreSQL integration tests. " +
                "No fallback or mock database is permitted.");
        }

        var builder = new NpgsqlConnectionStringBuilder(rawConnection)
        {
            Timeout = 5,
            CommandTimeout = 10
        };

        // Safety Guard 1: Host must be local
        var host = builder.Host?.Trim().ToLowerInvariant();
        if (host != "localhost" && host != "127.0.0.1" && host != "::1")
        {
            throw new InvalidOperationException(
                $"Host '{host}' is rejected. Integration tests are strictly restricted to local hosts (localhost/127.0.0.1/::1).");
        }

        // Safety Guard 2: Database must be an isolated test database
        var db = builder.Database?.Trim().ToLowerInvariant();
        if (string.IsNullOrWhiteSpace(db) || (!db.Equals("orai_webhooks_phase1_test") && !db.EndsWith("_test")))
        {
            throw new InvalidOperationException(
                $"Database '{db}' is rejected. Integration tests must target a dedicated test database (e.g. 'orai_webhooks_phase1_test').");
        }

        builder.SearchPath = _schemaName;
        _isolatedConnectionString = builder.ConnectionString;

        // Initialize isolated test schema and tables
        await using var initConn = new NpgsqlConnection(_isolatedConnectionString);
        await initConn.OpenAsync();

        var initSql = $"""
            CREATE SCHEMA IF NOT EXISTS {_schemaName};
            SET search_path TO {_schemaName}, public;

            CREATE TABLE IF NOT EXISTS webhook_inbox (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id uuid NOT NULL,
                endpoint_id uuid NOT NULL,
                payload_raw jsonb NOT NULL,
                headers jsonb NOT NULL,
                ip_address character varying(64),
                status smallint NOT NULL,
                attempt_count smallint NOT NULL,
                last_error text,
                lock_token uuid,
                locked_by character varying(64),
                locked_until timestamp with time zone,
                next_attempt_at timestamp with time zone NOT NULL,
                created_at timestamp with time zone NOT NULL,
                processed_at timestamp with time zone,
                pubsub_message_id character varying(128)
            );

            CREATE INDEX IF NOT EXISTS ix_webhook_inbox_queue
            ON webhook_inbox (next_attempt_at, created_at)
            WHERE status IN (0, 1);

            CREATE INDEX IF NOT EXISTS ix_webhook_inbox_failed_retry
            ON webhook_inbox (next_attempt_at, created_at)
            WHERE status = 3;

            CREATE UNIQUE INDEX IF NOT EXISTS ix_webhook_inbox_pubsub_message_id
            ON webhook_inbox (pubsub_message_id)
            WHERE pubsub_message_id IS NOT NULL;
            """;

        await initConn.ExecuteAsync(initSql);

        var inMemorySettings = new Dictionary<string, string?>
        {
            { "ConnectionStrings:DefaultConnection", _isolatedConnectionString }
        };

        var configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(inMemorySettings)
            .Build();

        _inboxRepository = new WebhookInboxRepository(configuration);
        _processorRepository = new WebhookProcessorRepository(configuration);
    }

    public async Task DisposeAsync()
    {
        if (!string.IsNullOrEmpty(_isolatedConnectionString))
        {
            try
            {
                await using var conn = new NpgsqlConnection(_isolatedConnectionString);
                await conn.OpenAsync();
                await conn.ExecuteAsync($"DROP SCHEMA IF EXISTS {_schemaName} CASCADE;");
            }
            catch
            {
                // Best-effort cleanup
            }
        }
    }

    private static PubSubWebhookEnvelope CreateSampleEnvelope(
        Guid? tenantId = null,
        Guid? endpointId = null,
        string? payload = null)
    {
        return PubSubWebhookEnvelope.Create(
            correlationId: Guid.NewGuid(),
            tenantId: tenantId ?? Guid.NewGuid(),
            endpointId: endpointId ?? Guid.NewGuid(),
            receivedAtUtc: DateTimeOffset.UtcNow,
            payloadRaw: payload ?? "{\"entry\":[{\"id\":\"test_payload\"}]}",
            rawHeaders: new Dictionary<string, string>
            {
                { "User-Agent", "facebookexternalua" },
                { "X-Forwarded-For", "127.0.0.1" },
                { "TraceParent", "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01" },
                { "Content-Type", "application/json" }
            },
            sourceIp: "127.0.0.1",
            contentType: "application/json"
        );
    }

    [Fact]
    public async Task EnqueueFromPubSubAsync_FirstInsert_ReturnsCreatedWithInboxId()
    {
        var envelope = CreateSampleEnvelope();
        var messageId = $"pubsub_msg_{Guid.NewGuid():N}";

        var result = await _inboxRepository.EnqueueFromPubSubAsync(envelope, messageId);

        result.Status.Should().Be(PubSubInboxEnqueueStatus.Created);
        result.InboxId.Should().BeGreaterThan(0);

        // Verify database contents
        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        var row = await conn.QuerySingleOrDefaultAsync<WebhookInboxItem>(
            "SELECT id, tenant_id AS TenantId, endpoint_id AS EndpointId, status, attempt_count AS AttemptCount, pubsub_message_id AS PubSubMessageId FROM webhook_inbox WHERE id = @Id",
            new { Id = result.InboxId });

        row.Should().NotBeNull();
        row!.TenantId.Should().Be(envelope.TenantId);
        row.EndpointId.Should().Be(envelope.EndpointId);
        row.Status.Should().Be(InboxStatus.Pending);
        row.AttemptCount.Should().Be(0);
        row.PubSubMessageId.Should().Be(messageId);
    }

    [Fact]
    public async Task EnqueueFromPubSubAsync_SequentialDuplicate_ReturnsAlreadyExistsWithOriginalInboxId()
    {
        var envelope = CreateSampleEnvelope();
        var messageId = $"pubsub_msg_seq_dup_{Guid.NewGuid():N}";

        var firstResult = await _inboxRepository.EnqueueFromPubSubAsync(envelope, messageId);
        firstResult.Status.Should().Be(PubSubInboxEnqueueStatus.Created);

        var secondResult = await _inboxRepository.EnqueueFromPubSubAsync(envelope, messageId);
        secondResult.Status.Should().Be(PubSubInboxEnqueueStatus.AlreadyExists);
        secondResult.InboxId.Should().Be(firstResult.InboxId);

        // Verify only 1 row exists in table for this message id
        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        var count = await conn.ExecuteScalarAsync<int>(
            "SELECT COUNT(*) FROM webhook_inbox WHERE pubsub_message_id = @MsgId",
            new { MsgId = messageId });

        count.Should().Be(1);
    }

    [Fact]
    public async Task EnqueueFromPubSubAsync_TrueConcurrentDuplicate_ProducesExactlyOneRowAndConsistentIds()
    {
        var envelope = CreateSampleEnvelope();
        var messageId = $"pubsub_msg_concurrent_{Guid.NewGuid():N}";

        // Run two concurrent tasks with separate repository instances
        var inMemorySettings = new Dictionary<string, string?>
        {
            { "ConnectionStrings:DefaultConnection", _isolatedConnectionString }
        };
        var config = new ConfigurationBuilder().AddInMemoryCollection(inMemorySettings).Build();

        var repo1 = new WebhookInboxRepository(config);
        var repo2 = new WebhookInboxRepository(config);

        var task1 = repo1.EnqueueFromPubSubAsync(envelope, messageId);
        var task2 = repo2.EnqueueFromPubSubAsync(envelope, messageId);

        var results = await Task.WhenAll(task1, task2);

        var res1 = results[0];
        var res2 = results[1];

        // Exactly one should be Created and one should be AlreadyExists
        var createdCount = results.Count(r => r.Status == PubSubInboxEnqueueStatus.Created);
        var alreadyExistsCount = results.Count(r => r.Status == PubSubInboxEnqueueStatus.AlreadyExists);

        createdCount.Should().Be(1);
        alreadyExistsCount.Should().Be(1);

        // Both must agree on the same InboxId
        res1.InboxId.Should().Be(res2.InboxId);

        // Verify database contains exactly 1 row
        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        var count = await conn.ExecuteScalarAsync<int>(
            "SELECT COUNT(*) FROM webhook_inbox WHERE pubsub_message_id = @MsgId",
            new { MsgId = messageId });

        count.Should().Be(1);
    }

    [Fact]
    public async Task EnqueueFromPubSubAsync_TwoDifferentMessageIds_CreatesTwoDistinctRows()
    {
        var envelope1 = CreateSampleEnvelope();
        var envelope2 = CreateSampleEnvelope();
        var msgId1 = $"pubsub_msg_diff1_{Guid.NewGuid():N}";
        var msgId2 = $"pubsub_msg_diff2_{Guid.NewGuid():N}";

        var res1 = await _inboxRepository.EnqueueFromPubSubAsync(envelope1, msgId1);
        var res2 = await _inboxRepository.EnqueueFromPubSubAsync(envelope2, msgId2);

        res1.Status.Should().Be(PubSubInboxEnqueueStatus.Created);
        res2.Status.Should().Be(PubSubInboxEnqueueStatus.Created);
        res1.InboxId.Should().NotBe(res2.InboxId);

        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        var totalCount = await conn.ExecuteScalarAsync<int>(
            "SELECT COUNT(*) FROM webhook_inbox WHERE pubsub_message_id IN (@Id1, @Id2)",
            new { Id1 = msgId1, Id2 = msgId2 });

        totalCount.Should().Be(2);
    }

    [Fact]
    public async Task ExistingWorker_CanClaimAndProcess_PubSubCreatedRow()
    {
        var envelope = CreateSampleEnvelope();
        var messageId = $"pubsub_worker_claim_{Guid.NewGuid():N}";

        var enqueueResult = await _inboxRepository.EnqueueFromPubSubAsync(envelope, messageId);
        enqueueResult.Status.Should().Be(PubSubInboxEnqueueStatus.Created);

        var lockToken = Guid.NewGuid();
        var claimed = await _processorRepository.ClaimBatchAsync(lockToken, "worker-pubsub-test", 10, 60);

        claimed.Should().Contain(x => x.Id == enqueueResult.InboxId);
        var item = claimed.First(x => x.Id == enqueueResult.InboxId);
        item.Status.Should().Be(InboxStatus.Processing);
        item.LockToken.Should().Be(lockToken);
    }

    [Fact]
    public async Task DirectIngestion_EnqueueAsync_RemainsUnchangedAndOperational()
    {
        var tenantId = Guid.NewGuid();
        var endpointId = Guid.NewGuid();
        var rawPayload = "{\"direct\":\"ingestion_test\"}";
        var headersJson = "{\"User-Agent\":\"WhatsApp/2.0\"}";

        var inboxId = await _inboxRepository.EnqueueAsync(
            tenantId,
            endpointId,
            rawPayload,
            headersJson,
            "127.0.0.1"
        );

        inboxId.Should().BeGreaterThan(0);

        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        var row = await conn.QuerySingleOrDefaultAsync<WebhookInboxItem>(
            "SELECT id, tenant_id AS TenantId, status, pubsub_message_id AS PubSubMessageId FROM webhook_inbox WHERE id = @Id",
            new { Id = inboxId });

        row.Should().NotBeNull();
        row!.TenantId.Should().Be(tenantId);
        row.Status.Should().Be(InboxStatus.Pending);
        row.PubSubMessageId.Should().BeNull(because: "Direct ingestion rows do not have a pubsub_message_id");
    }
}
