using Dapper;
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Npgsql;
using OraiWebhookManager.Application.Interfaces;
using OraiWebhookManager.Domain.Entities;
using OraiWebhookManager.Domain.Enums;
using OraiWebhookManager.Infrastructure.Persistence.Repositories;
using Xunit;

namespace OraiWebhookManager.IntegrationTests;

public class WebhookProcessorRepositoryIntegrationTests : IAsyncLifetime
{
    private readonly string _schemaName = $"test_phase1_{Guid.NewGuid():N}";
    private string _isolatedConnectionString = string.Empty;
    private IWebhookProcessorRepository _repository = null!;

    public async Task InitializeAsync()
    {
        var rawConnection = Environment.GetEnvironmentVariable("TEST_POSTGRES_CONNECTION");
        if (string.IsNullOrWhiteSpace(rawConnection))
        {
            throw new InvalidOperationException(
                "TEST_POSTGRES_CONNECTION environment variable is required to execute Phase 1 PostgreSQL integration tests. " +
                "No fallback or mock database is permitted.");
        }

        var builder = new NpgsqlConnectionStringBuilder(rawConnection)
        {
            Timeout = 5,
            CommandTimeout = 10
        };

        // Safety Guard 1: Host must be local
        var host = builder.Host?.Trim().ToLowerInvariant();
        if (host != "localhost" && host != "127.0.0.1" && host != "::1")
        {
            throw new InvalidOperationException(
                $"Host '{host}' is rejected. Integration tests are strictly restricted to local hosts (localhost/127.0.0.1/::1).");
        }

        // Safety Guard 2: Database must be an isolated test database
        var db = builder.Database?.Trim().ToLowerInvariant();
        if (string.IsNullOrWhiteSpace(db) || (!db.Equals("orai_webhooks_phase1_test") && !db.EndsWith("_test")))
        {
            throw new InvalidOperationException(
                $"Database '{db}' is rejected. Integration tests must target a dedicated test database (e.g. 'orai_webhooks_phase1_test').");
        }

        builder.SearchPath = _schemaName;
        _isolatedConnectionString = builder.ConnectionString;

        // Initialize isolated test schema and tables
        await using var initConn = new NpgsqlConnection(_isolatedConnectionString);
        await initConn.OpenAsync();

        var initSql = $"""
            CREATE SCHEMA IF NOT EXISTS {_schemaName};
            SET search_path TO {_schemaName}, public;

            CREATE TABLE IF NOT EXISTS webhook_inbox (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id uuid NOT NULL,
                endpoint_id uuid NOT NULL,
                payload_raw jsonb NOT NULL,
                headers jsonb NOT NULL,
                ip_address character varying(64),
                status smallint NOT NULL,
                attempt_count smallint NOT NULL,
                last_error text,
                lock_token uuid,
                locked_by character varying(64),
                locked_until timestamp with time zone,
                next_attempt_at timestamp with time zone NOT NULL,
                created_at timestamp with time zone NOT NULL,
                processed_at timestamp with time zone
            );

            CREATE INDEX IF NOT EXISTS ix_webhook_inbox_queue
            ON webhook_inbox (next_attempt_at, created_at)
            WHERE status IN (0, 1);

            CREATE INDEX IF NOT EXISTS ix_webhook_inbox_failed_retry
            ON webhook_inbox (next_attempt_at, created_at)
            WHERE status = 3;
            """;

        await initConn.ExecuteAsync(initSql);

        var inMemorySettings = new Dictionary<string, string?>
        {
            { "ConnectionStrings:DefaultConnection", _isolatedConnectionString }
        };

        var configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(inMemorySettings)
            .Build();

        _repository = new WebhookProcessorRepository(configuration);
    }

    public async Task DisposeAsync()
    {
        if (!string.IsNullOrEmpty(_isolatedConnectionString))
        {
            try
            {
                await using var conn = new NpgsqlConnection(_isolatedConnectionString);
                await conn.OpenAsync();
                await conn.ExecuteAsync($"DROP SCHEMA IF EXISTS {_schemaName} CASCADE;");
            }
            catch
            {
                // Best-effort cleanup
            }
        }
    }

    private async Task<long> InsertInboxItemAsync(
        short status,
        DateTimeOffset nextAttemptAt,
        short attemptCount = 0,
        Guid? lockToken = null,
        string? lockedBy = null,
        DateTimeOffset? lockedUntil = null,
        DateTimeOffset? createdAt = null)
    {
        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        const string insertSql = """
            INSERT INTO webhook_inbox (
                tenant_id, endpoint_id, payload_raw, headers, ip_address,
                status, attempt_count, last_error, lock_token, locked_by,
                locked_until, next_attempt_at, created_at, processed_at
            )
            VALUES (
                @TenantId, @EndpointId, CAST(@PayloadRaw AS jsonb), CAST(@Headers AS jsonb), @IpAddress,
                @Status, @AttemptCount, @LastError, @LockToken, @LockedBy,
                @LockedUntil, @NextAttemptAt, @CreatedAt, @ProcessedAt
            )
            RETURNING id;
            """;

        return await conn.ExecuteScalarAsync<long>(insertSql, new
        {
            TenantId = Guid.NewGuid(),
            EndpointId = Guid.NewGuid(),
            PayloadRaw = "{\"event\":\"test\"}",
            Headers = "{\"content-type\":\"application/json\"}",
            IpAddress = "127.0.0.1",
            Status = status,
            AttemptCount = attemptCount,
            LastError = status == (short)InboxStatus.Failed ? "Temporary network error" : null,
            LockToken = lockToken,
            LockedBy = lockedBy,
            LockedUntil = lockedUntil,
            NextAttemptAt = nextAttemptAt,
            CreatedAt = createdAt ?? DateTimeOffset.UtcNow,
            ProcessedAt = (DateTimeOffset?)null
        });
    }

    private async Task<WebhookInboxItem?> GetInboxItemAsync(long inboxId)
    {
        await using var conn = new NpgsqlConnection(_isolatedConnectionString);
        await conn.OpenAsync();

        const string selectSql = """
            SELECT id, status, attempt_count AS AttemptCount, last_error AS LastError,
                   lock_token AS LockToken, locked_until AS LockedUntil
            FROM webhook_inbox
            WHERE id = @Id;
            """;

        return await conn.QuerySingleOrDefaultAsync<WebhookInboxItem>(selectSql, new { Id = inboxId });
    }

    // 1. Due Failed item is claimed
    [Fact]
    public async Task ClaimBatchAsync_DueFailedStatus3Item_IsClaimed()
    {
        var pastDue = DateTimeOffset.UtcNow.AddSeconds(-30);
        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.Failed,
            nextAttemptAt: pastDue,
            attemptCount: 1
        );

        var lockToken = Guid.NewGuid();
        var claimed = await _repository.ClaimBatchAsync(lockToken, "worker-test-1", 10, 60);

        claimed.Should().Contain(x => x.Id == id);
        var item = claimed.First(x => x.Id == id);
        item.Status.Should().Be(InboxStatus.Processing);
        item.LockToken.Should().Be(lockToken);
        item.LockedBy.Should().Be("worker-test-1");
        item.LockedUntil.Should().BeAfter(DateTimeOffset.UtcNow);
    }

    // 2. Future Failed item is not claimed
    [Fact]
    public async Task ClaimBatchAsync_FutureFailedStatus3Item_IsNotClaimed()
    {
        var future = DateTimeOffset.UtcNow.AddMinutes(5);
        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.Failed,
            nextAttemptAt: future,
            attemptCount: 1
        );

        var lockToken = Guid.NewGuid();
        var claimed = await _repository.ClaimBatchAsync(lockToken, "worker-test-2", 10, 60);

        claimed.Should().NotContain(x => x.Id == id);
    }

    // 3. Pending item is claimed
    [Fact]
    public async Task ClaimBatchAsync_PendingStatus0Item_IsClaimed()
    {
        var pastDue = DateTimeOffset.UtcNow.AddSeconds(-5);
        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.Pending,
            nextAttemptAt: pastDue,
            attemptCount: 0
        );

        var lockToken = Guid.NewGuid();
        var claimed = await _repository.ClaimBatchAsync(lockToken, "worker-test-3", 10, 60);

        claimed.Should().Contain(x => x.Id == id);
        var item = claimed.First(x => x.Id == id);
        item.Status.Should().Be(InboxStatus.Processing);
        item.LockToken.Should().Be(lockToken);
    }

    // 4. Stale Processing lease is reclaimed
    [Fact]
    public async Task ClaimBatchAsync_StaleProcessingLease_IsReclaimed()
    {
        var expiredLease = DateTimeOffset.UtcNow.AddSeconds(-60);
        var pastDue = DateTimeOffset.UtcNow.AddSeconds(-120);
        var staleLockToken = Guid.NewGuid();

        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.Processing,
            nextAttemptAt: pastDue,
            attemptCount: 1,
            lockToken: staleLockToken,
            lockedBy: "dead-worker",
            lockedUntil: expiredLease
        );

        var newLockToken = Guid.NewGuid();
        var claimed = await _repository.ClaimBatchAsync(newLockToken, "new-worker", 10, 60);

        claimed.Should().Contain(x => x.Id == id);
        var item = claimed.First(x => x.Id == id);
        item.LockToken.Should().Be(newLockToken);
        item.LockedBy.Should().Be("new-worker");
    }

    // 5. Concurrent workers receive disjoint claims
    [Fact]
    public async Task ClaimBatchAsync_ConcurrentWorkers_ReceiveDisjointClaims()
    {
        var pastDue = DateTimeOffset.UtcNow.AddSeconds(-10);
        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.Failed,
            nextAttemptAt: pastDue,
            attemptCount: 2
        );

        var token1 = Guid.NewGuid();
        var token2 = Guid.NewGuid();

        var task1 = _repository.ClaimBatchAsync(token1, "worker-concurrent-1", 10, 60);
        var task2 = _repository.ClaimBatchAsync(token2, "worker-concurrent-2", 10, 60);

        var results = await Task.WhenAll(task1, task2);

        var worker1Items = results[0].Where(x => x.Id == id).ToList();
        var worker2Items = results[1].Where(x => x.Id == id).ToList();

        // Exactly one worker must claim the item (FOR UPDATE SKIP LOCKED)
        (worker1Items.Count + worker2Items.Count).Should().Be(1);
    }

    // 6. Fifth failure becomes DeadLetter
    [Fact]
    public async Task RecordFailureAsync_FifthFailure_BecomesDeadLetter()
    {
        var pastDue = DateTimeOffset.UtcNow.AddSeconds(-5);
        var lockToken = Guid.NewGuid();

        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.Processing,
            nextAttemptAt: pastDue,
            attemptCount: 4,
            lockToken: lockToken,
            lockedBy: "failing-worker",
            lockedUntil: DateTimeOffset.UtcNow.AddMinutes(2)
        );

        // Record failure as 5th attempt (maxAttempts = 5)
        await _repository.RecordFailureAsync(
            inboxId: id,
            lockToken: lockToken,
            errorMessage: "Persistent 500 error",
            attemptCount: 5,
            maxAttempts: 5
        );

        var row = await GetInboxItemAsync(id);
        row.Should().NotBeNull();
        row!.Status.Should().Be(InboxStatus.DeadLetter);
        row.AttemptCount.Should().Be(5);
        row.LastError.Should().Be("Persistent 500 error");
        row.LockToken.Should().BeNull();
        row.LockedUntil.Should().BeNull();
    }

    // 7. DeadLetter is never reclaimed
    [Fact]
    public async Task ClaimBatchAsync_DeadLetter_IsNeverReclaimed()
    {
        var longPast = DateTimeOffset.UtcNow.AddDays(-7);
        var id = await InsertInboxItemAsync(
            status: (short)InboxStatus.DeadLetter,
            nextAttemptAt: longPast,
            attemptCount: 5
        );

        var lockToken = Guid.NewGuid();
        var claimed = await _repository.ClaimBatchAsync(lockToken, "worker-test-dl", 10, 60);

        claimed.Should().NotContain(x => x.Id == id);
    }
}
